export default {
	"pages": {
		"root": {
			"id": "root",
			"pageUrl": "root",
			"name": "root",
			"children": [
				"6653970f3f24780021f73f01",
				"6653970f3f24780021f73f04"
			]
		},
		"6653970f3f24780021f73f01": {
			"id": "6653970f3f24780021f73f01",
			"name": "404",
			"pageUrl": "404"
		},
		"6653970f3f24780021f73f04": {
			"id": "6653970f3f24780021f73f04",
			"name": "index",
			"pageUrl": "index"
		}
	},
	"mode": "production",
	"projectType": "create-react-app",
	"site": {
		"styles": {},
		"seo": {
			"robotsFileType": "autogenerated"
		}
	}
}